import disnake
import sqlite3 as sql

from disnake.ext import commands 

class OnJoinFunctions(commands.Cog):
    def __init__(self,bot):
        self.bot=bot
        
        self.gother_terminal = self.bot.get_text_channel(861632215393763376)
        
        
    @commands.Cog.listener()
    async def on_guild_join(self, guild):
        self.gother_terminal.send(f'On Guild Join Function Triggered For {guild.name}')
        self.gother_terminal.send('Checking Categories Now. . .')
        
    
    async def cat_check(self, guild):
        name = [
            '=========Gawther=========',
            'announcements',
            'rules',
            'welcome',
            'change_log',
            '=========================',
            '========Show-Case========',
            'plugins',
            'themes',
            'art',
            'achievments',
            'awards',
            'trophies',
            '=========================',
            '======Holiday-Stuff======',
            '=========January=========',
            'new_years',
            'trivia_day',
            '=========February========',
            'groundhogs_day',
            'valentines_day',
            'chinese_new_year',
            'presidents_day',
            'mardi_gras',
            '==========March==========',
            'st_patricks_day',
            'earth_day',
            'spring_equinox',
            'passover',
            '==========April==========',
            'april_fools_day',
            'good_friday',
            'easter_sunday',
            'ramadan',
            'earth_day_us',
            '===========May===========',
            'may_day',
            'cinco_de_mayo',
            'national_teachers_day',
            'mothers_day',
            'armed_forces_day',
            'memorial_day',
            '===========June==========',
            'd_day_ww2',
            'summer_solstice',
            'fathers_day',
            '===========July==========',
            'canada_day',
            'independence_day',
            '=========August==========',
            'left_handers_day',
            '========September========',
            'vj_day_ww2',
            'labor_day',
            'grandparents_day',
            'oktoberfest_germany',
            'international_peace_day',
            'autumnal_equinox',
            'native_american_day',
            '=========October=========',
            'international_elderly_day',
            'world_smile_day',
            'indigenous_people_day',
            'thanksgiving_canada'
            'make_a_difference_day',
            'halloween',
            '=========November========',
            'dia_de_los_muertos',
            'all_souls_day',
            'veterans_day',
            'thanksgiving_us',
            'black_friday',
            '=========December========',
            'pearl_harbor_day',
            'winter_solstice',
            'christmas',
            'kwanzaa',
            'new_years_eve',
            '========================='
            '=====Code-Challenges=====',
            'python',
            'html_css',
            'javascript',
            'java',
            '=========================',
            '=======Suggestions=======',
            'how_to',
            'submit',
            'view_others',
            '=========================',
            '=========GLounge=========',
            'chat',
            'memes',
            'food',
            '420_friendly',
            'weather',
            '=========================',
            '=========G-Music=========',
            'radio1',
            'radio2',
            'radio3',
            'radio4',
            'v-radio1',
            'v-radio2',
            'v-radio3',
            'v-radio4',
            '=========================',
            '=========GGaming=========',
            '========Minecraft========',
            'announcements',
            'chat',
            'patterns',
            'accomplishments',
            'game_chat',
            '======VoiceChannels======',
            'one',
            'two',
            'three',
            'four',
            'five',
            'six',
            'seven',
            'eight',
            'nine',
            'ten',
            '=========================',
            '======Summoners-War======',
            'announcements',
            'chat',
            'arena_hook_up',
            'raid_hook_up',
            'add_me',
            'accomplishments',
            'most_proud_of',
            '======VoiceChannels======',
            'one',
            'two',
            'three',
            'four',
            'five',
            'six',
            'seven',
            'eight',
            'nine',
            'ten',
            '=========================',
            '========Factorio!========',
            'announcements',
            'blueprints',
            'servers',
            'setups',
            'chat',
            '======VoiceChannels======',
            'one',
            'two',
            'three',
            'four',
            'five',
            'six',
            'seven',
            'eight',
            'nine',
            'ten',
            '=========================',
            '=========Support=========',
            'how_to',
            'que',
            'alpha',
            'bravo',
            'charlie',
            'delta',
            'echo',
            'frank',
            'golf',
            'hotel',
            'igloo',
            'juliet',
            'kilo',
            'lima',
            'mike',
            'november',
            'oscar',
            'papa',
            'quebec',
            'romeo',
            'sierra',
            'tango',
            'uniform',
            'victor',
            'whiskey',
            'x-ray',
            'yankee',
            'zulu',
            '=========================',
            '==========Staff==========',
            'announcements',
            'reminders',
            'rules',
            'info_per_role',
            'chat',
            '======VoiceChannels======',
            'one',
            'two',
            'three',
            'four',
            '=========================',
            '========Developers=======',
            'announcements',
            'reminders',
            'notes',
            'file_swap',
            'member_suggestions',
            'chat',
            '======VoiceChannels======',
            'one',
            'two',
            'three',
            'four',
            '=========================',
            '===========Logs==========',
            'gother_terminal',
            'warning_logs',
            'mute_logs',
            'kick_logs',
            'ban_logs',
            'audit_logs',
            'bugs',
            '========================='
        ]
    
    
    async def cat_write(self, guild):
        pass
    
    
    async def chan_check(self, cat):
        pass
    
    
    async def chan_write(self, cat):
        pass
    
    
    async def write_members(self, guild):
        pass